=== JohnGF/nautilus_bci/manuals/gHIsys/Examples/ParadigmPresenter/xsd/ParadigmSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"
           targetNamespace="xsd"
           xmlns:xsi="xsd"
           elementFormDefault="qualified">


	<!-- TYPE DEFINITIONS -->

  <!-- Stimuli -->

	<xs:complexType name="Stimulus" abstract="true">
    <xs:attribute name="UdpMessage" type="xs:string"/>
    <xs:attribute name="LslMessage" type="xs:string"/>
  </xs:complexType>

	<xs:complexType name="VisualStimulus" abstract="true">
		<xs:complexContent>
			<xs:extension base="xsi:Stimulus">
				<xs:attribute name="HorizontalAlignment"    type="xsi:HorizontalAlignment"   default="Center"/>
				<xs:attribute name="VerticalAlignment"      type="xsi:VerticalAlignment"     default="Center"/>
				<xs:attribute name="Scaling"                type="xsi:Scaling"               default="Manual"/>
				<xs:attribute name="ManualScalingPercent"   type="xsi:NonNegativeDouble"     default="100"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="StaticVisualStimulus" abstract="true">
		<xs:complexContent>
			<xs:extension base="xsi:VisualStimulus">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="PictureStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:StaticVisualStimulus">
				<xs:attribute name="FileName" type="xs:string"  use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="TextStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:StaticVisualStimulus">
				<xs:attribute name="Caption"     type="xs:string"     default=""/>
				<xs:attribute name="Color"       type="xsi:HexRGB"    default="FFFFFF"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AudioStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:Stimulus">
				<xs:attribute name="FileName"      type="xs:string"                   use="required"/>
				<xs:attribute name="VolumePercent" type="xsi:Max100NonNegativeDouble" default="100"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="VideoStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:VisualStimulus">
				<xs:attribute name="VolumePercent" type="xsi:Max100NonNegativeDouble" default="100"/>
				<xs:attribute name="FileName"      type="xs:string"                   use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Port">
		<xs:attribute name="Index"       type="xsi:DigitalOutPortIndex"  use="required"/>
		<xs:attribute name="FrequencyHz" type="xsi:NonNegativeDouble"    default="0"/>
	</xs:complexType>

	<xs:complexType name="DigitalOutStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:Stimulus">
				<xs:choice minOccurs="1" maxOccurs="16">
					<xs:element name="Port" type="xsi:Port"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


  <!-- Contexts -->
  <xs:complexType name="Contexts">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Context" type="xsi:Context"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Context">
    <xs:attribute name="ID" type="xs:string" use="required"/>
    <xs:attribute name="TargetGroup" type="xs:string" use="required"/>
    <xs:attribute name="DelaySeconds" type="xs:double" use="required"/>
    <xs:attribute name="DurationSeconds" type="xsi:NonNegativeDouble" use="required"/>
  </xs:complexType>

	<!-- Tasks -->
	<xs:complexType name="Node" abstract="true">
		<xs:attribute name="Label"   type="xs:string"   default=""/>
	</xs:complexType>

	<xs:complexType name="GenericTask" abstract="true">
		<xs:complexContent>
			<xs:extension base="xsi:Node">
				<xs:attribute name="Multiplicity" type="xs:positiveInteger"  default="1"/>
				<xs:attribute name="ID"           type="xs:NCName"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- SingleTask -->
	<xs:complexType name="SingleTask" mixed="true">
		<xs:complexContent>
			<xs:extension base="xsi:GenericTask">
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="Stimulus" type="xsi:Stimulus" minOccurs="0">
            <xs:unique name="UniquePortKey">
              <xs:selector xpath="xsi:Port" />
              <xs:field xpath="@Index" />
            </xs:unique>
          </xs:element>
        </xs:sequence>
				<xs:attribute name="Group"           type="xs:nonNegativeInteger" default="0"/>
				<xs:attribute name="DurationSeconds"                              default="1">
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minInclusive value="0.01"/>
							<xs:maxInclusive value="1200"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<!-- MultiTask -->
	<xs:complexType name="MultiTask" mixed="true">
		<xs:complexContent>
			<xs:extension base="xsi:GenericTask">
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="Task" type="xsi:GenericTask"/>
				</xs:choice>
				<xs:attribute name="TaskOrder"    type="xsi:TaskOrder"         default="Deterministic"/>
				<xs:attribute name="SampleSize"   type="xs:nonNegativeInteger" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<!-- Paradigm -->
	<xs:complexType name="Paradigm" mixed="true">
		<xs:complexContent>
			<xs:extension base="xsi:Node">
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="Task" type="xsi:GenericTask"/>
				</xs:choice>
				<xs:attribute name="TaskOrder"             type="xsi:TaskOrder"         default="Deterministic" />
				<xs:attribute name="SampleSize"            type="xs:nonNegativeInteger" default="0"/>
				<xs:attribute name="BaseFolder"            type="xs:string"             default="./"/>
				<xs:attribute name="BackgroundColor"       type="xsi:HexRGB"            default="000000"/>
				<xs:attribute name="UdpAddress"            type="xs:string"             use="optional"/>
        <xs:attribute name="UdpPort"               type="xs:nonNegativeInteger" use="optional"/>
        <xs:attribute name="LslStreamName"         type="xs:string"             use="optional"/>
      </xs:extension>
		</xs:complexContent>
	</xs:complexType>





	<!-- Additional Groups/Types -->

	<xs:simpleType name="HexRGB">
		<xs:restriction base="xs:hexBinary">
			<xs:length value="3"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HorizontalAlignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Left"/>
			<xs:enumeration value="Center"/>
			<xs:enumeration value="Right"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="VerticalAlignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Top"/>
			<xs:enumeration value="Center"/>
			<xs:enumeration value="Bottom"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Scaling">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fit"/>
			<xs:enumeration value="Fill"/>
			<xs:enumeration value="Stretch"/>
			<xs:enumeration value="Manual"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="NonNegativeDouble">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Max100NonNegativeDouble">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="DigitalOutPortIndex">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="15"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="TaskOrder">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Deterministic"/>
			<xs:enumeration value="RandomWithReplacement"/>
			<xs:enumeration value="RandomWithoutReplacement"/>
		</xs:restriction>
	</xs:simpleType>

  

	<xs:complexType name="XmlData" mixed="true">
    <xs:all>
      <xs:element name="Paradigm"   type="xsi:Paradigm"   minOccurs="1"/>
      <xs:element name="Contexts"    type="xsi:Contexts"  minOccurs="0" />
    </xs:all>
  </xs:complexType>



	<!-- ELEMENT DEFINITION -->

	<xs:element name="Data" type="xsi:XmlData">

	</xs:element>


</xs:schema>

=== JohnGF/nautilus_bci/docs/vendor-manuals/gHIsys/Examples/ParadigmPresenter/AEP/AEP_simple_UDP.xml
<?xml version="1.0" encoding="utf-8"?>
<Data xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ../../ParadigmSchema.xsd">
  <Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_Pre" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+"/>
    </Task>
    <Task ns:type="MultiTask" ID="MT_Paradigm" TaskOrder="Deterministic" SampleSize="250">
	  <Task ns:type="SingleTask" ID="ST_Target" DurationSeconds="0.2">
		  <Stimulus ns:type="AudioStimulus" FileName="Target_trigleft.wav" UdpMessage="1"/>
      </Task>
      <Task ns:type="SingleTask" ID="ST_Baseline" DurationSeconds="0.8"/>  
    </Task>
  </Paradigm>
</Data>

=== JohnGF/nautilus_bci/docs/vendor-manuals/gHIsys/Examples/ParadigmPresenter/VEP/Checkerboard_simple.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd"
           xmlns:ns="http://www.w3.org/2001/XMLSchema-instance"
           ns:schemaLocation="xsd ../ParadigmSchema.xsd">
  <Paradigm BaseFolder="media/" TaskOrder="Deterministic">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+"/>
    </Task>
    <Task ns:type="MultiTask" ID="MT_Wrapper" TaskOrder="Deterministic" SampleSize="300">
	   <Task ns:type="SingleTask" ID="ST_Target" DurationSeconds="0.15">
         <Stimulus ns:type="PictureStimulus" FileName="CheckerBoard1.png"/>
       </Task>
       <Task ns:type="SingleTask" ID="ST_Dark" DurationSeconds="0.85">
       </Task>
    </Task>
  </Paradigm>
</Data>

=== JohnGF/nautilus_bci/manuals/gHIsys/Examples/ParadigmPresenter/Eyetracker/xml/Eyetracking.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd"
           xmlns:ns="http://www.w3.org/2001/XMLSchema-instance"
           ns:schemaLocation="xsd ../../ParadigmSchema.xsd">

  <Paradigm BaseFolder="media/" TaskOrder="Deterministic">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+"/>
    </Task>
	  <Task ns:type="MultiTask" ID="MT_TaskSequence" TaskOrder="Deterministic" SampleSize="32">
		  <Task ns:type="MultiTask" ID="MT_Move" TaskOrder="RandomWithoutReplacement" SampleSize="1">
			  <Task ns:type="SingleTask" ID="ST_REST1" DurationSeconds="2.75" Group="5">
				<Stimulus ns:type="TextStimulus" Caption="+"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_REST2" DurationSeconds="2.875" Group="5">
				<Stimulus ns:type="TextStimulus" Caption="+"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_REST3" DurationSeconds="3" Group="5">
				<Stimulus ns:type="TextStimulus" Caption="+"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_REST4" DurationSeconds="3.125" Group="5">
				<Stimulus ns:type="TextStimulus" Caption="+"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_REST5" DurationSeconds="3.25" Group="5">
				<Stimulus ns:type="TextStimulus" Caption="+"/>
			  </Task>
		  </Task>
		  <Task ns:type="MultiTask" ID="MT_Distract" TaskOrder="RandomWithoutReplacement" SampleSize="1">
			  <Task ns:type="SingleTask" ID="ST_TL" DurationSeconds="3" Group="1">
			    <Stimulus ns:type="PictureStimulus" FileName="TL.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_TR" DurationSeconds="3" Group="2">
			    <Stimulus ns:type="PictureStimulus" FileName="TR.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_BL" DurationSeconds="3" Group="3">
			    <Stimulus ns:type="PictureStimulus" FileName="BL.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100"/>
			  </Task>
			  <Task ns:type="SingleTask" ID="ST_BR" DurationSeconds="3" Group="4">
			    <Stimulus ns:type="PictureStimulus" FileName="BR.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100"/>
			  </Task>
		  </Task>
	  </Task>
    <Task ns:type="SingleTask" ID="ST_PostParadigm" DurationSeconds="50"  Group="6">
      <Stimulus ns:type="TextStimulus" Caption="Thank You!"/>
    </Task>
  </Paradigm>

</Data>

=== JohnGF/nautilus_bci/manuals/gHIsys/Examples/ParadigmPresenter/VEP/Checkerboard_UDP.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ../ParadigmSchema.xsd">
  <Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+"/>
    </Task>
    <Task ns:type="MultiTask" ID="MT_Wrapper" TaskOrder="Deterministic" SampleSize="300">
	   <Task ns:type="SingleTask" ID="ST_Target" DurationSeconds="0.15">
         <Stimulus ns:type="PictureStimulus" FileName="CheckerBoard1.png" UdpMessage="1"/>
       </Task>
	   <Task ns:type="SingleTask" ID="ST_NonTarget" DurationSeconds="0.85">
         <Stimulus ns:type="PictureStimulus" FileName="CheckerBoard2.png" UdpMessage="2"/>
       </Task>
    </Task>
  </Paradigm>
</Data>

=== JohnGF/nautilus_bci/docs/vendor-manuals/gHIsys/Examples/ParadigmPresenter/Video/VideoParadigm_testdata.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd"
           xmlns:ns="http://www.w3.org/2001/XMLSchema-instance"
           ns:schemaLocation="xsd C:\_SVN\ECoGmeToo\trunk\sources\ParadigmTools\src\main\Paradigm\ParadigmSchema.xsd">

  <Paradigm BaseFolder="media/">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+"/>
    </Task>
    <Task ns:type="SingleTask" ID="ST_Video" DurationSeconds="50" Group="1">
      <Stimulus ns:type="VideoStimulus" FileName="video_testdata.mp4"/>
    </Task>
    <Task ns:type="SingleTask" ID="ST_PostParadigm" DurationSeconds="5">
      <Stimulus ns:type="TextStimulus" Caption="Thank You!"/>
    </Task>
  </Paradigm>

</Data>

=== JohnGF/nautilus_bci/manuals/gHIsys/Examples/ParadigmPresenter/AEP/AEP_gRecorder.xml
<?xml version="1.0" encoding="utf-8"?>
<Data xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ../ParadigmSchema.xsd">
  <Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+" />
    </Task>
    <Task ns:type="MultiTask" ID="MT_Sequence" TaskOrder="RandomWithoutReplacement" SampleSize="90">
      <Task ns:type="MultiTask" ID="MT_Target" TaskOrder="Deterministic" SampleSize="2">
        <Task ns:type="SingleTask" ID="ST_Target" DurationSeconds="0.25" Group="1">
          <Stimulus ns:type="AudioStimulus" FileName="Target.wav" UdpMessage="gR(1)"/>
        </Task>
        <Task ns:type="SingleTask" ID="ST_TargetSpacer" DurationSeconds="0.25" Group="0"/>
      </Task>
      <Task ns:type="MultiTask" ID="MT_NonTarget" TaskOrder="Deterministic" SampleSize="2" Multiplicity="8">
        <Task ns:type="SingleTask" ID="ST_NonTarget" DurationSeconds="0.25" Group="2">
          <Stimulus ns:type="AudioStimulus" FileName="Nontarget.wav" UdpMessage="gR(2)"/>
        </Task>
        <Task ns:type="SingleTask" ID="ST_NonTargetSpacer" DurationSeconds="0.25" Group="0"/>
      </Task>
    </Task>
    <Task ns:type="SingleTask" ID="ST_PostParadigm" DurationSeconds="5">
      <Stimulus ns:type="TextStimulus" Caption="Thank You!" />
    </Task>
  </Paradigm>
</Data>

=== JohnGF/nautilus_bci/docs/vendor-manuals/gHIsys/Examples/ParadigmPresenter/Vibrotactile/Vibrotactile.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd"
           xmlns:ns="http://www.w3.org/2001/XMLSchema-instance"
           ns:schemaLocation="xsd ../ParadigmSchema.xsd">

  <Paradigm TaskOrder="Deterministic">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+" />
    </Task>
  	<Task ns:type="MultiTask" ID="MT_All" TaskOrder="Deterministic" SampleSize="400">
		<Task ns:type="MultiTask" ID="MT_Stim" TaskOrder="RandomWithoutReplacement" SampleSize="1">
			<Task ns:type="SingleTask" ID="ST_Finger1" DurationSeconds="0.2" Group="1">
				<Stimulus ns:type="DigitalOutStimulus">
					<Port Index="1"/>
				</Stimulus>
			</Task>
			<Task ns:type="SingleTask" ID="ST_Finger2" DurationSeconds="0.2" Group="2">
				<Stimulus ns:type="DigitalOutStimulus">
					<Port Index="2"/>
				</Stimulus>
			</Task>
			<Task ns:type="SingleTask" ID="ST_Finger3" DurationSeconds="0.2" Group="3">
				<Stimulus ns:type="DigitalOutStimulus">
					<Port Index="3"/>
				</Stimulus>
			</Task>
			<Task ns:type="SingleTask" ID="ST_Finger4" DurationSeconds="0.2" Group="4">
				<Stimulus ns:type="DigitalOutStimulus">
					<Port Index="4"/>
				</Stimulus>
			</Task>
			<Task ns:type="SingleTask" ID="ST_Finger5" DurationSeconds="0.2" Group="5">
				<Stimulus ns:type="DigitalOutStimulus">
					<Port Index="5"/>
				</Stimulus>
			</Task>
		</Task>
		<Task ns:type="MultiTask" ID="MT_Pause" TaskOrder="RandomWithReplacement" SampleSize="1">
			<Task ns:type="SingleTask" ID="ST_Pause1" DurationSeconds="1.0"   Group="0"/>
			<Task ns:type="SingleTask" ID="ST_Pause2" DurationSeconds="1.125" Group="0"/>
			<Task ns:type="SingleTask" ID="ST_Pause3" DurationSeconds="1.25"  Group="0"/>
			<Task ns:type="SingleTask" ID="ST_Pause4" DurationSeconds="1.375" Group="0"/>
			<Task ns:type="SingleTask" ID="ST_Pause5" DurationSeconds="1.5"   Group="0"/>
      </Task>
    </Task>
    <Task ns:type="SingleTask" ID="ST_PostParadigm" DurationSeconds="5">
      <Stimulus ns:type="TextStimulus" Caption="Thank You!" />
    </Task>
  </Paradigm>
</Data>
